---
- name: Install Pip
  become: yes
  package:
    name: python-pip
    state: present

- name: Install Ansible with Pip
  become: yes
  pip:
    name:
      - ansible
      - pywinrm
    state: present

- name: Remove Ansible package
  become: yes
  package:
    name: ansible
    state: absent